### ISSUE TITLE
Listagem de animais

### ISSUE THREAD

**Issue by CarvalhoCa** [CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6#3]
As pessoas de Salto interessadas em adotar um pet precisam de  uma lista com filtro de animais disponíveis para adoção para facilitar e/ou intermediar esse processo:

- [x] Ligação ou consulta ao banco de dados
  - [x] Modelo Entidade Relacionamento (MER) ou Esquema dos Documentos não Relacionais
  - [x] Dicionário de Dados
  - [x] Criar a base de dados
  - [x] Popular a base de dados 
  - [x] Consulta ao Banco
  - [ ] Impressão da consulta na página
- [ ] Filtro por tipo de animais ( idade, tamanho, raça, cor, espécie )
  - [x] Diagrama de Classes Relacionados aos Filtros
  - [x] Diagrama de Caso de Uso
  - [x] Diagramas de Sequência 
  - [x] Implementar os Objetos Responsáveis pelo Filtro
  - [ ] Imprimir os filtros na página 
- [ ] Galeria de fotos do animal
  - [x] Diagrama de Classes Relacionados as Fotos dos Animais
  - [x] Diagrama de Caso de Uso
  - [x] Diagramas de Sequência 
  - [ ] Implementar os Objetos Responsáveis pela Galeria de Fotos 
  - [ ] Consulta de Fotos
  - [ ] Impressão da consulta na página 

*Critérios de aceite:
Bom exemplo: Todas as fotos do animal cadastradas no sistema devem aparecer em sua galeria de fotos.

Os filtros e carregamentos das fotos funcionando corretamente. **O que é o funcionando corretamente?**

_**Diagrama de Casos de Uso Filtro**_
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20Casos%20de%20uso%20Filtro.pdf

**_Diagrama Casos de Uso Galeria Fotos_**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20casos%20de%20uso%20galeria%20de%20fotos.pdf

**_Diagrama de Classes Galeria Fotos_** 
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20classe%20galeria%20de%20fotos.pdf

**_Diagrama de Classes de Filtro_**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20classes%20Filtro.pdf

** Banco de Dados MySQL Workbench_**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/BD%20Petsgram.sql

** Dicionário de Banco de dados**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Dicion%C3%A1rio%20de%20dados%20Petsgram.docx

**Comment by CarvalhoCa** [comment]
Hoje Fizemos alguns Diagramas

Diagrama de Casos de Uso Filtro
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20Casos%20de%20uso%20Filtro.pdf

Diagrama Casos de Uso Galeria Fotos
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20casos%20de%20uso%20galeria%20de%20fotos.pdf

Diagrama de Classes Galeria Fotos
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20classe%20galeria%20de%20fotos.pdf

Diagrama de Classes de Filtro
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20de%20classes%20Filtro.pdf

**Comment by davifma** [comment]
Se vocês já criaram a base e polularam já estão "fazendo".

**Comment by davifma** [comment]
Normalmente temos um "Diagrama de Caso de Uso" para todo o sistema.

Diagrama de Classes também normalmente é um só por sistema

Na classe "Foto" provavelmente você teria uma propriedade Booleana para "favorita".

Para mim pareceu que a classe "Usuário" está relacionada a "Animal" e não a "Filtro".

**Comment by CarvalhoCa** [comment]
Um novo Diagrama de Casos de Uso

https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20Casos%20de%20Uso%20PetsGram.pdf

**Comment by CarvalhoCa** [comment]
Diagrama de classe atualizado

https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20classes%20PetsGram.pdf

**Comment by davifma** [comment]
Tá bem legal gente, só uns pontos de atenção.

Para mim ficou confuso o que são os métodos Animal.buscarAnimais() e Filtro.aplicar()

O que relaciona a Galeria com o Animal? Algum atributo faz essa relação?

Eu preciso saber quem adotou cada animal? Se sim, como é feita essa relação?

**Comment by CarvalhoCa** [comment]
**Banco de Dados MySQL Workbench_**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/BD%20Petsgram.sql

** Dicionário de Banco de dados**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Dicion%C3%A1rio%20de%20dados%20Petsgram.docx

**Modelo Entidade Relacionamento**
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Modelo%20Entidade%20Relacionamento.pdf

**Comment by davifma** [comment]
No dicionário de dados o Usuário não tem endereço e no modelo sim, qual está correto?

No dicionário de dados temos uma tabela raça, no modelo não.

No dicionário de dados temos uma tabela espécie, no modelo não.

Os campos da tabela animal e animais estão diferentes em ambos os documentos.

As tabelas devem ter os mesmo nomes no dicionário de dados e nos diagramas, por exemplo "Animal" nos dois, por convenção nomes de tabelas são sempre no singular.

Não entendi a lista de relações no final do dicionário de dados.

Acho que o dicionário está de acordo com o banco criado, mas não bate com o diagrama, a impressão é que o banco foi criado antes do resto. Além disso não há chaves estrangeiras nas tabelas de raça e espécie no banco também.

**Comment by Mary-Alves** [comment]
--No dicionário de dados o Usuário não tem endereço e no modelo sim, qual está correto?
 **endereço inserido no BD e no dicionário!



--Os campos da tabela animal e animais estão diferentes em ambos os documentos.
--As tabelas devem ter os mesmo nomes no dicionário de dados e nos diagramas, por exemplo "Animal" nos dois, por convenção nomes de tabelas são sempre no singular
 ** alterei os campos onde estavam "animais" para 'animal', tanto no BD quanto no dicionário!

https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/BD%20Petsgram%20atualizado.sql




--Acho que o dicionário está de acordo com o banco criado, mas não bate com o diagrama, a impressão é que o banco foi criado antes do resto. Além disso não há chaves estrangeiras nas tabelas de raça e espécie no banco também.
**chave estrangeira está na tabela animais.

CREATE TABLE animais (
id INT PRIMARY KEY,
raca_id INT,
tamanho VARCHAR(50),
cor VARCHAR(50),
idade INT,
especie_id INT,
FOREIGN KEY (raca_id) REFERENCES raca(id),
FOREIGN KEY (especie_id) REFERENCES especie(id)
);
creio q no dicionário coloquei trocado, alterei!

https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/dicionario%20Banco%20de%20Dados%20Pet'sGram%20Atualizado1.xlsx



-- Não entendi a lista de relações no final do dicionário de dados. 
** ela relaciona, no BD, somente a tabela 'animal' com as tabelas 'raca' e 'especie', pq na tabela 'animal' esta a chave estrangeira das duas outras tabelas. :/

**Comment by CarvalhoCa** [comment]
Entidade e Relacionamento atualizado

https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Diagrama%20entidade%20e%20relacionamento%20atualizado.drawio.pdf
