### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by CarvalhoCa** [CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6#5]
Como usuário eu necessito de tela de login intuitiva para acessar o site.

- [x] Design de tela de login

- [ ] Codificação da interface

- [ ] Ligação com banco de dados

- [ ] Cadastrar usuário

**Comment by CarvalhoCa** [comment]
Hoje finalizamos esses Diagramas

Diagrama de sequência Login atualizado
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Login%20Sequence%20Diagrama%20atual.pdf

Diagrama de estado Login
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/diagrama%20de%20estado%20login-logout.pdf

**Comment by CarvalhoCa** [comment]
Código de login  atualizado

file:///D:/4%20semestre/Analise%20e%20desenv%20sistemas%20II%20-%20Davi/login.html

**Comment by davifma** [comment]
Se já tem código está em Fazendo...

**Comment by davifma** [comment]
Por que o código está em TXT?
O diagrama de estados está correto, dependendo de como o sistema for implementado, todavia ele era necessário?
O diagrama de sequência mostra três camadas View, Controller e Model, o código do TXT não está nem usando classes, quanto mais 3 camadas de classe. O Código deve refletir a documentação e vice-versa.

**Comment by Mary-Alves** [comment]
https://github.com/CarvalhoCa/Analise-e-Projetos-de-Sistemas---Grupo-6/blob/main/Login%20Sequence%20Diagrama%20atual.pdf

diagrama de sequencia atualizado.

**Comment by davifma** [comment]
Não autenticado é um único estado. Então o diagrama deveria retornar.
![Image](https://github.com/user-attachments/assets/c20f9db3-e10f-4ef7-a197-317622d5a19a)

Como o código, embora esteja dentro de um objeto, não está orientado a objetos de fato é difícil compreender a utilidade dos diagramas.

**Comment by Mary-Alves** [comment]
atualização do código de login

file:///D:/4%20semestre/Analise%20e%20desenv%20sistemas%20II%20-%20Davi/login.html
